Replace custom FutureLift with monix-catnap implementation
cr-org/neutron pull request #111
Opened 2020-11-15 23:07 UTC by psisoyev

Also cleaned up effect type bounds, now we don't ask for ```Concurrent: ContextShift``` everywhere

2020-11-15 23:25 UTC, agjacome commented on core/src/main/scala/cr/pulsar/internal/FutureLift.scala
> +import java.util.concurrent.{ CompletableFuture, _ }
Auto-importing mess up?. The `_` is no longer needed, just leave the `CompletableFuture`.

2020-11-15 23:26 UTC, agjacome approved these changes

2020-11-16 08:34 UTC, gvolpe requested changes
I'm :-1: on this. We change `ContextShift` for `FutureLift`, which is not part of `cats-effect`, and we are also adding yet another dependency.

2020-11-16 09:23 UTC, psisoyev commented
An extra dependency seems a bit too much, I agree

2020-11-16 09:23 UTC, closed without merging